-- MySQL setup script
-- Run this script to set up the database schema and indexes
-- Warning: This file is automatically generated, do not modify it.

CREATE TABLE `campaigns` (
    `id` VARCHAR(255) PRIMARY KEY,
    `goal` BIGINT,
    `raised` BIGINT,
    `is_complete` BOOLEAN,
    `completion_txid` VARCHAR(255)
);

CREATE TABLE `investments` (
    `id` VARCHAR(255) PRIMARY KEY,
    `campaign_id` VARCHAR(255),
    `identity_key` VARCHAR(255),
    `amount` BIGINT,
    `timestamp` BIGINT,
    `redeemed` BOOLEAN
);

CREATE INDEX `ix_investments_s_1` ON `investments`(`campaign_id` ASC);
CREATE INDEX `ix_investments_s_2` ON `investments`(`identity_key` ASC);

CREATE TABLE `dynamic_configuration` (
    `config_key` VARCHAR(255) PRIMARY KEY,
    `config_value` MEDIUMTEXT
);

CREATE TABLE `sessions` (
    `id` VARCHAR(255) PRIMARY KEY,
    `secret` VARCHAR(255),
    `uid` VARCHAR(255),
    `created` BIGINT,
    `expiration` BIGINT,
    `tfa_pending` BOOLEAN,
    `remote` VARCHAR(255),
    `browser` VARCHAR(255),
    `os` VARCHAR(255)
);

CREATE INDEX `ix_sessions_s_1` ON `sessions`(`uid`);

CREATE TABLE `user_profile` (
    `id` VARCHAR(255) PRIMARY KEY,
    `name` VARCHAR(255),
    `bio` TEXT,
    `image` VARCHAR(255),
    `location` VARCHAR(255),
    `website` VARCHAR(255)
);

CREATE TABLE `user_roles` (
    `id` VARCHAR(255) PRIMARY KEY,
    `permissions` TEXT
);

CREATE TABLE `tp_users` (
    `id` VARCHAR(255) PRIMARY KEY,
    `uid` VARCHAR(255),
    `type` VARCHAR(255),
    `tp_email` VARCHAR(255),
    `tp_username` VARCHAR(255),
    `profile_name` VARCHAR(255),
    `secret` VARCHAR(255)
);

CREATE INDEX `ix_tp_users_s_1` ON `tp_users`(`uid`);

CREATE TABLE `users` (
    `id` VARCHAR(255) PRIMARY KEY,
    `username` VARCHAR(255),
    `username_lower_case` VARCHAR(255),
    `email` VARCHAR(255),
    `email_verified` BOOLEAN,
    `email_verification_code` VARCHAR(255),
    `email_request` VARCHAR(255),
    `password_hash` VARCHAR(255),
    `password_salt` VARCHAR(255),
    `password_reset_code` VARCHAR(255),
    `password_reset_expiration` BIGINT,
    `role` VARCHAR(255),
    `banned` BOOLEAN,
    `tfa` BOOLEAN,
    `tfa_secret` VARCHAR(255),
    `created` BIGINT,
    `locale` VARCHAR(255),
    `wallet_provider` VARCHAR(255),
    `wallet_identity_key` VARCHAR(255)
);

CREATE UNIQUE INDEX `ix_users_s_1` ON `users`(`username_lower_case`);
CREATE UNIQUE INDEX `ix_users_s_2` ON `users`(`email`);
CREATE INDEX `ix_users_s_3` ON `users`(`role`);
CREATE UNIQUE INDEX `ix_users_s_4` ON `users`(`wallet_identity_key`);

CREATE TABLE `wallets` (
    `id` VARCHAR(255) PRIMARY KEY,
    `uid` VARCHAR(255),
    `name` VARCHAR(255),
    `address` VARCHAR(255),
    `encrypted_key` TEXT,
    `password_hash` VARCHAR(255),
    `password_salt` VARCHAR(255)
);

CREATE INDEX `ix_wallets_s_1` ON `wallets`(`uid`);

CREATE TABLE `tokens` (
    `id` VARCHAR(255) PRIMARY KEY,
    `name` VARCHAR(255),
    `symbol` VARCHAR(255),
    `decimals` INT,
    `totalSupply` BIGINT,
    `maxSupply` BIGINT,
    `creatorIdentityKey` VARCHAR(255),
    `createdAt` BIGINT,
    `metadataJson` TEXT,
    `genesisTxid` VARCHAR(255),
    `genesisVout` INT
);

CREATE INDEX `ix_tokens_s_1` ON `tokens`(`creatorIdentityKey` ASC);
CREATE INDEX `ix_tokens_s_2` ON `tokens`(`symbol` ASC);

CREATE TABLE `token_holders` (
    `id` VARCHAR(255) PRIMARY KEY,
    `tokenId` VARCHAR(255),
    `holderIdentityKey` VARCHAR(255),
    `balance` BIGINT,
    `lastUpdated` BIGINT
);

CREATE INDEX `ix_token_holders_s_1` ON `token_holders`(`tokenId` ASC);
CREATE INDEX `ix_token_holders_s_2` ON `token_holders`(`holderIdentityKey` ASC);

CREATE TABLE `token_transactions` (
    `id` VARCHAR(255) PRIMARY KEY,
    `tokenId` VARCHAR(255),
    `type` VARCHAR(255),
    `fromIdentityKey` VARCHAR(255),
    `toIdentityKey` VARCHAR(255),
    `amount` BIGINT,
    `txid` VARCHAR(255),
    `vout` INT,
    `timestamp` BIGINT,
    `notes` TEXT,
    `spentBy` VARCHAR(255)
);

CREATE INDEX `ix_token_transactions_s_1` ON `token_transactions`(`tokenId` ASC);
CREATE INDEX `ix_token_transactions_s_2` ON `token_transactions`(`toIdentityKey` ASC);
CREATE INDEX `ix_token_transactions_s_3` ON `token_transactions`(`txid` ASC);
